### ISSUE TITLE
Port the recent commits in a Nuget update.

### ISSUE THREAD

**Issue by GitHubProUser67** [space-wizards/ManagedHttpListener#5]
Sorry to create an issue for this, but can you update the last nuget package with the recent PRs? It would allow me to use the nuget directly and reducing the project size that way.

Thanks in advance.

**Comment by PJB3005** [comment]
Done, give it a couple minutes for NuGet to finish publishing it https://www.nuget.org/packages/SpaceWizards.HttpListener/0.2.0

**Comment by GitHubProUser67** [comment]
Thank you a lot! I really like it.
